version: '3.3'
services:
  adminer:
    image: adminer
    container_name: postgres_UI
    restart: always
    ports:
      - ''

  db:
    image: postgres:13.10
    container_name: postgres_db
    env_file: .env
    restart: always
    shm_size: 128mb
    ports:
      - ''
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: analytics_app_backend
    container_name: django_app
    env_file: .env
    ports:
      - ''
    command: bash -c ""
    depends_on:
      - db

  web:
    build: ./front
    image: analytics_app_frontend
    container_name: react_app
    ports:
      - ''
    depends_on:
      - backend

volumes:
  pgdata:
