services:
  db:
    image: postgres
    container_name: postgres_db
    env_file: .env
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: postgres_UI
    restart: always
    ports:
      - 8080:8080

  web:
    container_name: react_app
    build: ./front
    ports:
      - '3000:3000'
    volumes:
      - ./front:/front
    depends_on:
      - backend
      
  backend:
    container_name: backend
    build: ./backend
    env_file: .env
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    networks:
      - myNetwork
    volumes:
      - ./nginx:/nginx
    ports:
      - '1337:1337'
    depends_on:
      - backend

volumes:
  pgdata:

# создаём сеть.
networks:
  myNetwork:
    driver: bridge
