# Generated by Django 4.2.16 on 2024-12-26 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_by_employee_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
