# Generated by Django 4.2.16 on 2024-12-27 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_tariffs', '0004_loan_created_by_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='created_by_employee_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_by_employee_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
