# Generated by Django 4.2.16 on 2024-12-27 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_tariffs', '0005_bank_created_by_employee_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='created_by_employee_email',
            new_name='employee_username',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='created_by_employee_email',
            new_name='employee_username',
        ),
        migrations.AddField(
            model_name='bank',
            name='created_by_employee_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
