# Generated by Django 4.2.16 on 2024-12-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_campaign', '0002_remove_campaigninfo_targetcustomer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigninfo',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
