# Generated by Django 4.2.16 on 2024-12-27 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_campaign', '0003_alter_campaigninfo_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfo',
            name='created_by_employee_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
