# Generated by Django 4.2.16 on 2024-12-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_campaign', '0004_campaigninfo_created_by_employee_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfo',
            name='created_by_employee_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
