# Generated by Django 4.2.16 on 2024-12-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_campaign', '0005_campaigninfo_created_by_employee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigninfo',
            old_name='created_by_employee_email',
            new_name='employee_username',
        ),
    ]
